services:
  - type: web
    name: audio-separator
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17
      - key: CUDA_VISIBLE_DEVICES
        value: ""


